version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17  # Amazon Corretto is a no-cost, multiplatform, production-ready 
                        # distribution of the Open Java Development Kit (OpenJDK)
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install     # This command instructs Apache Maven to compile, test, and package the 
                        # compiled Java class files into a build output artifact.
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/hello-world-war-1.0.0.war
